language: perl
perl:
   - "5.24"
   - "5.22"
   - "5.20"
   - "5.18"
before_install:
   - cpanm --notest --skip-satisfied Devel::Cover::Report::Coveralls
script:
   perl Makefile.PL && make && cover -test -report coveralls
