language: perl
perl:
   - "5.24"
   - "5.22"
   - "5.20"
   - "5.18"

before_install:
   - sudo add-apt-repository ppa:olithered/gpsbabel -y
   - sudo apt-get -qq update
   - sudo apt-get install -y gpsbabel
   - cpan-install --coverage

before_script:
   - coverage-setup

after_success:
   - coverage-report

matrix:
   include:
      - perl: 5.24
        env: COVERAGE=1
