language: perl
perl:
   - "5.24"
   - "5.22"
   - "5.20"
   - "5.18"
before_install:
   - cpanm --notest --skip-satisfied Devel::Cover::Report::Coveralls
   - apt-get -qq update
   - apt-get install -y gpsbabel
script:
   perl Makefile.PL && make && cover -test -report coveralls
