language: perl
perl:
   - "5.24"
   - "5.22"
   - "5.20"
   - "5.18"
before_install:
   - sudo add-apt-repository ppa:olithered/gpsbabel -y
   - sudo apt-get -qq update
   - sudo apt-get install -y gpsbabel
   - cpanm --notest --skip-satisfied Devel::Cover::Report::Coveralls
script:
   perl Makefile.PL && make

matrix:
   include:
      - perl: 5.24
        env: COVERAGE=1
